using icon on card view headers
TheLastProject/Catima pull request #585
Opened 2021-11-12 17:25 UTC by Kethen

some previews
![image](https://user-images.githubusercontent.com/22017945/141508586-9cf1a1e7-6312-4bea-8362-16f0bbed2a27.png)
![image](https://user-images.githubusercontent.com/22017945/141508626-b97fd7bd-701b-4fe8-8883-23f71489c57a.png)
![image](https://user-images.githubusercontent.com/22017945/141508668-790d0038-d6ae-429b-9c9b-efdb341ad1e3.png)
![image](https://user-images.githubusercontent.com/22017945/141508688-10c1ee3f-c215-4955-b941-16d94ef87e60.png)
![image](https://user-images.githubusercontent.com/22017945/141508745-c344bd7d-b0db-4d53-b98d-495a3b43423f.png)
![image](https://user-images.githubusercontent.com/22017945/141508774-7bdb111f-e3c2-41d0-87b3-4f75b067840b.png)

2021-11-12 23:14 UTC, TheLastProject requested changes
There are a few glitches, but mostly works great. I feel we should probably be able to display a bit of the picture below the header bar too though, but I spent the past... 4+ hours trying to get that to work and I just couldn't without breaking other parts of the UI so... low-prio anyway I guess.

This one though... I have no clue:

![image](https://user-images.githubusercontent.com/1885159/141519249-5cbc3b06-60fe-4436-92f3-10733e945d74.png)

It happened with this image:
![dog_hendrik_sticker_512](https://user-images.githubusercontent.com/1885159/141519342-1e00367e-ceae-4340-abdf-540daa2240ef.png)

2021-11-13 03:14 UTC, Kethen commented on app/src/main/res/layout/loyalty_card_view_layout.xml
> +        </RelativeLayout>
Setting the relative layout to invisible might solve it, I'll take a look later

2021-11-13 05:29 UTC, Kethen commented
https://user-images.githubusercontent.com/1885159/141519249-5cbc3b06-60fe-4436-92f3-10733e945d74.png
I need more information on this one, the image sets fine on my emulator
Meanwhile I don't think poking the image out of the top bar looks good, but I can change it to that way if you think it looks better

2021-11-13 13:28 UTC, TheLastProject commented
All I know is that the dog thing spams my Android Studio console:

```
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:id/icon_image} during second layout pass: posting in next frame
D/onLayoutChange: collapsing toolbar change, height: 481
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ......ID 0,0-1080,496 #7f0902c2 app:id/icon_image} during layout: running second layout pass
D/onLayoutChange: collapsing toolbar change, height: 481
D/onGlobalLayout: checking if bottom sheet size has to be changed
D/Catima: Button sheet should be 1448 pixels high
W/View: requestLayout() improperly called by androidx.appcompat.widget.AppCompatImageView{ed01abb V.ED..... ........ 0,0-1080,496 #7f0902c2 app:i [...]

2021-11-14 14:18 UTC, Kethen commented
![image](https://user-images.githubusercontent.com/22017945/141685035-4ed2a537-536a-4822-99b1-fbd76a9e2e5f.png)

2021-11-14 14:44 UTC, TheLastProject approved these changes

2021-11-14 14:45 UTC, TheLastProject commented
bors r+

2021-11-14 14:50 UTC, merged