671 adding English to list of languages, relaunch main activity after language change
TheLastProject/Catima pull request #677
Opened 2021-12-13 11:43 UTC by Kethen

#671 please review

2021-12-13 15:12 UTC, Altonss requested changes
I just tested the changes on my Android 5.0.2 device and noticed that now after the language has been changed, the MainActivity is displayed (with the correct language) instead of the settings view like before. Is this a wanted change to close the settings and open MainActivity after a language change?

2021-12-13 17:44 UTC, TheLastProject requested changes

2021-12-13 17:44 UTC, TheLastProject commented on app/src/main/java/protect/card_locker/preferences/SettingsActivity.java
> +                Intent intent = new Intent(getContext(), MainActivity.class);
I think we need to add something to MainActivity that will open another activity, so we can go back to settings while force-reloading main too. That way we can also fix #607 in the same go.

2021-12-14 17:38 UTC, TheLastProject commented
Oh clever, when something is changed that needs the MainActivity to recreate you pretty much just mark it for when moving back from SettingActivity, so you don't reload more than needed even if someone changes the setting twice in a row before leaving SettingsActivity.

Very clean :)

bors r+

2021-12-14 17:43 UTC, merged